name: Task
description: Create a new technical task
title: "[Task]: "
body:
  - type: textarea
    id: done-when
    attributes:
      label: Done when (checklist)
      value: "- [ ] "
    validations:
      required: true
  - type: input
    id: where-in-code
    attributes:
      label: Where in the code
    validations:
      required: true
  - type: input
    id: epic
    attributes:
      label: Epic